-- Add missing columns to customers table
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS customer_value VARCHAR(20) DEFAULT 'standard';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS urgency_level VARCHAR(20) DEFAULT 'normal';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS priority_score INTEGER DEFAULT 50;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS ai_score INTEGER DEFAULT 50;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(20) DEFAULT 'hi';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS preferred_dialect VARCHAR(40);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS do_not_call INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS consent_status VARCHAR(20) DEFAULT 'unknown';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_contact_outcome VARCHAR(40);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS scheduled_datetime TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS wrong_number_flag INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS admin_review_required INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS callback_requested_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_called_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS best_call_slot VARCHAR(10);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_pickup_slot VARCHAR(10);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS pickup_rate_score INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS outstanding_issues TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS pending_follow_ups TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_sentiment_score REAL;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_sentiment_label VARCHAR(20);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS revenue_stage VARCHAR(30) DEFAULT 'unassigned';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS revenue_estimate REAL DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS campaign_name VARCHAR(100);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS service_interest VARCHAR(100);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS call_type VARCHAR(50) DEFAULT 'REVIEW_CALL';
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_competitor_mention TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS data_retention_until TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS dnd_checked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS default_agent_id INTEGER;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS video_sent INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS attempt_count INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS failed_reason TEXT;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS normalized_phone VARCHAR(20);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS auto_retry_enabled INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS locked_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS provider_request_id VARCHAR(100);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS is_manual INTEGER DEFAULT 0;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS last_visit_date DATE;

-- Add missing columns to clients table
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS annual_reminder_enabled INTEGER DEFAULT 1;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS annual_reminder_slot VARCHAR(10) DEFAULT '10:00';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS next_annual_reminder_date DATE;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS last_annual_reminder_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS last_annual_reminder_year INTEGER;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS linked_customer_id INTEGER;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'active';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;

-- Add missing columns to calls table
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(100);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'pending';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS call_direction VARCHAR(20) DEFAULT 'outbound';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS call_source VARCHAR(40) DEFAULT 'icallmate';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS did VARCHAR(40);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS answered_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS ended_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS media_packets INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS last_event VARCHAR(40);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS provider_payload_json TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS transcript_text TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS consent_detected INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS language VARCHAR(10);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS extracted_rating INTEGER;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS extracted_review_text TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS feedback_saved_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS recording_sid VARCHAR(100);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS recording_url TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS recording_status VARCHAR(30);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS recording_local_path TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS transcript_status VARCHAR(30) DEFAULT 'pending';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS transcript_source VARCHAR(20);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS analysis_status VARCHAR(30) DEFAULT 'pending';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS analysis_summary TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS analysis_json TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS key_points_json TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS report_excerpt TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS analysis_completed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS outcome_detail VARCHAR(40);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS fallback_triggered INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS sentiment_label VARCHAR(20);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS sentiment VARCHAR(20);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS sentiment_score REAL;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS call_duration INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS call_end_reason VARCHAR(50);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS ai_talk_time INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS patient_talk_time INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS quality_score INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS timeline_events TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS extracted_entities TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS hot_lead_score INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS next_action_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS follow_up_task TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS uuid VARCHAR(36);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS recording_download_status VARCHAR(30) DEFAULT 'pending';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS crm_sync_status VARCHAR(30) DEFAULT 'pending';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS revenue_attribution_status VARCHAR(30) DEFAULT 'pending';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS call_script_version VARCHAR(40) DEFAULT 'hindi-feedback-v1';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS call_type VARCHAR(50) DEFAULT 'REVIEW_CALL';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS competitor_mentions_json TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS objections_json TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS interest_detected INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS callback_requested INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS human_escalation_requested INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS supervisor_alert_level VARCHAR(20) DEFAULT 'normal';
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS supervisor_notes TEXT;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS consent_message_played INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS recording_consent_captured INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS invoice_triggered INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS proposal_triggered INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS live_sentiment_score REAL;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS live_sentiment_label VARCHAR(20);
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS live_red_flag INTEGER DEFAULT 0;
ALTER TABLE public.calls ADD COLUMN IF NOT EXISTS agent_id INTEGER;

-- Add missing columns to feedback table
ALTER TABLE public.feedback ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'manual';

-- Re-grant permissions just in case
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
