const PDFDocument = require('pdfkit');
const fs = require('fs');

const COLORS = {
  ink: '#15233b',
  muted: '#6e7e99',
  line: '#d9e4f2',
  soft: '#f6f9ff',
  blue: '#2d6df6',
  blueSoft: '#e9f1ff',
  green: '#2ea043',
  greenSoft: '#eaf7ee',
  orange: '#ff9b17',
  orangeSoft: '#fff2df',
  red: '#ea5455',
  redSoft: '#ffe8e8',
  panel: '#ffffff',
  dark: '#14213d'
};

function resolveFontPath() {
  const candidates = [
    '/System/Library/Fonts/Supplemental/Arial Unicode.ttf',
    '/Library/Fonts/Arial Unicode.ttf'
  ];

  return candidates.find((fontPath) => fs.existsSync(fontPath)) || null;
}

function registerFonts(doc) {
  const unicodeFontPath = resolveFontPath();
  if (unicodeFontPath) {
    doc.registerFont('ReportUnicode', unicodeFontPath);
    return { regular: 'ReportUnicode', heading: 'ReportUnicode' };
  }

  return { regular: 'Helvetica', heading: 'Helvetica-Bold' };
}

function setFont(doc, fonts, type = 'regular', size = 10, color = COLORS.ink) {
  doc.font(type === 'heading' ? fonts.heading : fonts.regular)
    .fontSize(size)
    .fillColor(color);
}

function drawPanel(doc, x, y, width, height, fill = COLORS.panel, stroke = COLORS.line, radius = 18) {
  doc.save();
  doc.roundedRect(x, y, width, height, radius).fillAndStroke(fill, stroke);
  doc.restore();
}

function drawWatermark(doc, fonts, text) {
  if (!text) return;

  const centerX = doc.page.width / 2;
  const centerY = doc.page.height / 2;

  doc.save();
  doc.fillOpacity(0.06);
  doc.rotate(-32, { origin: [centerX, centerY] });
  doc.font(fonts.heading).fontSize(54).fillColor(COLORS.blue);
  doc.text(text, centerX - 240, centerY - 28, {
    width: 480,
    align: 'center',
    lineBreak: false
  });
  doc.restore();
}

function drawFooter(doc, fonts) {
  const footerY = doc.page.height - doc.page.margins.bottom - 12;
  setFont(doc, fonts, 'regular', 8, COLORS.muted);
  doc.text('Generated by Feedback Automation System', 40, footerY, {
    width: doc.page.width - 80,
    align: 'center',
    lineBreak: false
  });
}

function decoratePage(doc, fonts, watermarkText) {
  drawWatermark(doc, fonts, watermarkText);
  drawFooter(doc, fonts);
}

function addPage(doc, fonts, watermarkText) {
  doc.addPage();
  decoratePage(doc, fonts, watermarkText);
  doc.y = 46;
}

function getBottomLimit(doc) {
  return doc.page.height - doc.page.margins.bottom - 28;
}

function ensureSpace(doc, fonts, watermarkText, requiredHeight) {
  if (doc.y + requiredHeight <= getBottomLimit(doc)) {
    return;
  }

  addPage(doc, fonts, watermarkText);
}

function safeNumber(value, fallback = 0) {
  return Number.isFinite(Number(value)) ? Number(value) : fallback;
}

function formatPercent(value) {
  return `${safeNumber(value).toFixed(1)}%`;
}

function formatDate(value) {
  if (!value) return 'N/A';
  return new Date(value).toLocaleString();
}

function drawHeader(doc, fonts, reportData, watermarkText) {
  drawPanel(doc, 40, 34, doc.page.width - 80, 124, COLORS.dark, COLORS.dark, 28);

  setFont(doc, fonts, 'regular', 12, '#c8d8ff');
  doc.text('Daily Feedback Report', 66, 56);

  setFont(doc, fonts, 'heading', 27, '#ffffff');
  doc.text(watermarkText, 66, 78, { width: doc.page.width - 132 });

  setFont(doc, fonts, 'regular', 11, '#dce6ff');
  doc.text(`Report date: ${new Date(reportData.date || Date.now()).toLocaleDateString()}`, 66, 118);
  doc.text(`Prepared at: ${new Date().toLocaleString()}`, 66, 136);

  if (reportData.dashboard_link) {
    setFont(doc, fonts, 'regular', 10, '#c8d8ff');
    doc.text('Open dashboard', doc.page.width - 165, 118, {
      link: reportData.dashboard_link,
      underline: true
    });
  }

  doc.y = 178;
}

function drawSectionTitle(doc, fonts, title, subtitle, watermarkText) {
  ensureSpace(doc, fonts, watermarkText, 46);
  setFont(doc, fonts, 'heading', 16, COLORS.ink);
  doc.text(title, 40, doc.y);

  if (subtitle) {
    setFont(doc, fonts, 'regular', 9, COLORS.muted);
    doc.text(subtitle, 40, doc.y + 4);
  }

  doc.moveDown(1.3);
}

function drawExecutiveSummary(doc, fonts, reportData, watermarkText) {
  drawSectionTitle(doc, fonts, 'Executive Summary', 'Daily operational overview and customer sentiment snapshot', watermarkText);
  ensureSpace(doc, fonts, watermarkText, 92);

  const y = doc.y;
  drawPanel(doc, 40, y, doc.page.width - 80, 76, COLORS.soft, COLORS.line, 20);

  setFont(doc, fonts, 'regular', 11, COLORS.ink);
  doc.text(reportData.summary_text || 'No executive summary available.', 60, y + 18, {
    width: doc.page.width - 120,
    align: 'left'
  });

  setFont(doc, fonts, 'regular', 9, COLORS.muted);
  doc.text(
    `Feedback captured: ${safeNumber(reportData.feedback_count)} | Average rating: ${safeNumber(reportData.average_rating).toFixed(1)}/5 | Success rate: ${formatPercent(reportData.success_rate)}`,
    60,
    y + 48,
    { width: doc.page.width - 120 }
  );

  doc.y = y + 96;
}

function drawSuccessAndRating(doc, fonts, reportData, watermarkText) {
  drawSectionTitle(doc, fonts, 'Success Rate + Average Rating', 'Operational conversion and customer sentiment at a glance', watermarkText);
  ensureSpace(doc, fonts, watermarkText, 130);

  const y = doc.y;
  const width = (doc.page.width - 96) / 2;
  const successRate = safeNumber(reportData.success_rate);
  const averageRating = safeNumber(reportData.average_rating);

  drawPanel(doc, 40, y, width, 108, COLORS.panel, COLORS.line, 20);
  setFont(doc, fonts, 'regular', 10, COLORS.muted);
  doc.text('Answer Success Rate', 58, y + 16);
  setFont(doc, fonts, 'heading', 25, COLORS.ink);
  doc.text(formatPercent(successRate), 58, y + 36);
  doc.save();
  doc.roundedRect(58, y + 74, width - 36, 12, 6).fill('#edf3fb');
  doc.roundedRect(58, y + 74, Math.max(8, (width - 36) * Math.min(successRate, 100) / 100), 12, 6).fill(COLORS.blue);
  doc.restore();

  drawPanel(doc, 56 + width, y, width, 108, COLORS.panel, COLORS.line, 20);
  setFont(doc, fonts, 'regular', 10, COLORS.muted);
  doc.text('Average Rating', 74 + width, y + 16);
  setFont(doc, fonts, 'heading', 25, COLORS.ink);
  doc.text(`${averageRating.toFixed(1)}/5`, 74 + width, y + 36);
  setFont(doc, fonts, 'regular', 10, COLORS.muted);
  doc.text(`Based on ${safeNumber(reportData.feedback_count)} feedback entries`, 74 + width, y + 72);

  doc.y = y + 126;
}

function drawBreakdownBar(doc, fonts, x, y, label, count, pct, color) {
  setFont(doc, fonts, 'regular', 10, COLORS.muted);
  doc.text(label, x, y);
  setFont(doc, fonts, 'heading', 10, COLORS.ink);
  doc.text(`${count} (${pct}%)`, x + 248, y, { width: 120, align: 'right' });

  doc.save();
  doc.roundedRect(x, y + 18, 368, 12, 6).fill('#edf3fb');
  const barWidth = pct > 0 ? (368 * pct) / 100 : 0;
  if (barWidth > 0) {
    doc.roundedRect(x, y + 18, barWidth, 12, 6).fill(color);
  }
  doc.restore();
}

function drawFeedbackBreakdown(doc, fonts, reportData, watermarkText) {
  const good = safeNumber(reportData.good_count);
  const average = safeNumber(reportData.average_count);
  const bad = safeNumber(reportData.bad_count);
  const total = good + average + bad;
  const goodPct = total > 0 ? Number(((good / total) * 100).toFixed(1)) : 0;
  const averagePct = total > 0 ? Number(((average / total) * 100).toFixed(1)) : 0;
  const badPct = total > 0 ? Number(((bad / total) * 100).toFixed(1)) : 0;

  drawSectionTitle(doc, fonts, 'Feedback Breakdown', 'Distribution of good, average, and bad customer responses', watermarkText);
  ensureSpace(doc, fonts, watermarkText, 168);

  const y = doc.y;
  drawPanel(doc, 40, y, doc.page.width - 80, 138, COLORS.soft, COLORS.line, 20);
  drawBreakdownBar(doc, fonts, 60, y + 22, 'Good', good, goodPct, COLORS.green);
  drawBreakdownBar(doc, fonts, 60, y + 60, 'Average', average, averagePct, COLORS.orange);
  drawBreakdownBar(doc, fonts, 60, y + 98, 'Bad', bad, badPct, COLORS.red);
  doc.y = y + 156;
}

function drawBulletList(doc, fonts, items, watermarkText, emptyText) {
  const rows = Array.isArray(items) ? items.filter(Boolean) : [];
  if (!rows.length) {
    ensureSpace(doc, fonts, watermarkText, 72);
    const y = doc.y;
    drawPanel(doc, 40, y, doc.page.width - 80, 56, COLORS.soft, COLORS.line, 16);
    setFont(doc, fonts, 'regular', 10, COLORS.muted);
    doc.text(emptyText, 60, y + 20);
    doc.y = y + 72;
    return;
  }

  rows.forEach((item) => {
    const height = Math.max(44, doc.heightOfString(item, { width: doc.page.width - 130 }) + 20);
    ensureSpace(doc, fonts, watermarkText, height + 10);
    const y = doc.y;
    drawPanel(doc, 40, y, doc.page.width - 80, height, COLORS.panel, COLORS.line, 16);
    doc.save();
    doc.circle(62, y + 20, 4).fill(COLORS.blue);
    doc.restore();
    setFont(doc, fonts, 'regular', 10, COLORS.ink);
    doc.text(item, 78, y + 12, { width: doc.page.width - 140 });
    doc.y = y + height + 10;
  });
}

function drawKeyInsights(doc, fonts, reportData, watermarkText) {
  drawSectionTitle(doc, fonts, 'Key Insights', 'High-signal observations extracted from analyzed calls', watermarkText);
  const insights = (reportData.analyzed_calls || [])
    .map((call) => call.analysis_summary || call.report_excerpt)
    .filter(Boolean)
    .slice(0, 6);

  drawBulletList(doc, fonts, insights, watermarkText, 'No AI insights available yet for this report window.');
}

function drawAlerts(doc, fonts, reportData, watermarkText) {
  drawSectionTitle(doc, fonts, 'Alerts / Pending Items', 'Items that still need operator follow-up or pipeline completion', watermarkText);
  const items = (reportData.pending_items || []).map((item) => {
    const parts = [
      `${item.customer_name || 'Customer'} at ${formatDate(item.called_at)}`,
      `Outcome: ${item.outcome || 'n/a'}`,
      `Recording: ${item.recording_status || 'pending'}`,
      `Transcript: ${item.transcript_status || 'pending'}`,
      `Analysis: ${item.analysis_status || 'pending'}`
    ];

    return parts.join(' | ');
  });

  drawBulletList(doc, fonts, items, watermarkText, 'No pending alerts. Recording, transcript, and analysis pipeline look healthy.');
}

function drawCallDetailCard(doc, fonts, call, watermarkText) {
  const detailLines = [
    `Customer: ${call.customer_name || 'Customer'} | Called at: ${formatDate(call.called_at)}`,
    `Outcome: ${call.outcome || 'n/a'} | Rating: ${call.extracted_rating || 'N/A'}/5`,
    `Recording: ${call.recording_status || 'pending'} | Transcript: ${call.transcript_status || 'pending'} | Analysis: ${call.analysis_status || 'pending'}`
  ];

  const transcriptPreview = call.transcript_text
    ? call.transcript_text.replace(/\s+/g, ' ').slice(0, 180)
    : 'Transcript pending or unavailable.';
  const baseHeight = 118;
  const previewHeight = doc.heightOfString(transcriptPreview, { width: doc.page.width - 140 });
  const cardHeight = Math.max(baseHeight, 92 + previewHeight);

  ensureSpace(doc, fonts, watermarkText, cardHeight + 12);
  const y = doc.y;
  drawPanel(doc, 40, y, doc.page.width - 80, cardHeight, COLORS.panel, COLORS.line, 18);

  let lineY = y + 16;
  detailLines.forEach((line) => {
    setFont(doc, fonts, lineY === y + 16 ? 'heading' : 'regular', lineY === y + 16 ? 11 : 9, lineY === y + 16 ? COLORS.ink : COLORS.muted);
    doc.text(line, 58, lineY, { width: doc.page.width - 116 });
    lineY += lineY === y + 16 ? 22 : 18;
  });

  // setFont(doc, fonts, 'regular', 10, COLORS.ink);
  // doc.text(`Transcript preview: ${transcriptPreview}`, 58, y + 74, {
  //   width: doc.page.width - 116
  // });

  const linkY = y + cardHeight - 24;
  if (call.recording_link) {
    setFont(doc, fonts, 'regular', 9, COLORS.blue);
    doc.text('Recording link', 58, linkY, { link: call.recording_link, underline: true });
  }
  if (call.transcript_link) {
    setFont(doc, fonts, 'regular', 9, COLORS.blue);
    doc.text('Transcript link', 148, linkY, { link: call.transcript_link, underline: true });
  }

  doc.y = y + cardHeight + 10;
}

function drawCallDetails(doc, fonts, reportData, watermarkText) {
  drawSectionTitle(doc, fonts, 'Call Details', 'Operational call records with quick access to recordings and transcripts', watermarkText);
  const calls = Array.isArray(reportData.analyzed_calls) ? reportData.analyzed_calls.slice(0, 6) : [];

  if (!calls.length) {
    drawBulletList(doc, fonts, [], watermarkText, 'No call details available for this report window.');
    return;
  }

  calls.forEach((call) => drawCallDetailCard(doc, fonts, call, watermarkText));
}

function drawDashboardLink(doc, fonts, reportData, watermarkText) {
  if (!reportData.dashboard_link) {
    return;
  }

  // drawSectionTitle(doc, fonts, 'Dashboard Link', 'Jump directly into the live admin console for recordings, pipeline status, and actions', watermarkText);
  ensureSpace(doc, fonts, watermarkText, 82);

  const y = doc.y;
  drawPanel(doc, 40, y, doc.page.width - 80, 64, COLORS.blueSoft, '#bfd4ff', 18);
  setFont(doc, fonts, 'heading', 11, COLORS.blue);
  doc.text('Open Admin Dashboard', 60, y + 16, {
    link: reportData.dashboard_link,
    underline: true
  });
  setFont(doc, fonts, 'regular', 10, COLORS.muted);
  doc.text(reportData.dashboard_link, 60, y + 34, { width: doc.page.width - 120 });
  doc.y = y + 82;
}

function generateReportPDF(reportData) {
  return new Promise((resolve, reject) => {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const reportPath = `/tmp/report_${timestamp}.pdf`;
      const doc = new PDFDocument({
        margin: 40,
        size: 'A4',
        autoFirstPage: true
      });
      const stream = fs.createWriteStream(reportPath);
      const fonts = registerFonts(doc);
      const watermarkText = process.env.CLIENT_NAME || 'Client';

      doc.pipe(stream);
      decoratePage(doc, fonts, watermarkText);

      drawHeader(doc, fonts, reportData, watermarkText);
      drawExecutiveSummary(doc, fonts, reportData, watermarkText);
      drawSuccessAndRating(doc, fonts, reportData, watermarkText);
      drawFeedbackBreakdown(doc, fonts, reportData, watermarkText);
      drawKeyInsights(doc, fonts, reportData, watermarkText);
      drawAlerts(doc, fonts, reportData, watermarkText);
      drawCallDetails(doc, fonts, reportData, watermarkText);
      drawDashboardLink(doc, fonts, reportData, watermarkText);

      doc.end();

      stream.on('finish', () => {
        console.log(`✓ PDF report generated: ${reportPath}`);
        resolve(reportPath);
      });

      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
}

function formatDuration(seconds) {
  const total = Math.max(0, Math.round(Number(seconds || 0)));
  const minutes = Math.floor(total / 60);
  const remainingSeconds = total % 60;
  return minutes ? `${minutes}m ${remainingSeconds}s` : `${remainingSeconds}s`;
}

function drawCallAnalysisHeader(doc, fonts, call, analysis, watermarkText) {
  drawPanel(doc, 40, 34, doc.page.width - 80, 132, COLORS.dark, COLORS.dark, 24);
  setFont(doc, fonts, 'regular', 11, '#c8d8ff');
  doc.text('Call Analysis Report', 64, 56);
  setFont(doc, fonts, 'heading', 24, '#ffffff');
  doc.text(call.customer_name || 'Patient', 64, 78, { width: doc.page.width - 128 });
  setFont(doc, fonts, 'regular', 10, '#dce6ff');
  doc.text(`Phone: ${call.customer_phone || ''}`, 64, 112);
  doc.text(`Call type: ${analysis.call_type_label || call.call_type || ''}`, 64, 130);
  doc.text(`Outcome: ${call.outcome || ''} | Quality: ${analysis.quality_score || 0}%`, 300, 112);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 300, 130);
  doc.y = 188;
}

function drawAnalysisSummary(doc, fonts, call, analysis, watermarkText) {
  drawSectionTitle(doc, fonts, 'Summary', 'AI-generated operational summary', watermarkText);
  ensureSpace(doc, fonts, watermarkText, 96);
  const y = doc.y;
  drawPanel(doc, 40, y, doc.page.width - 80, 78, COLORS.soft, COLORS.line, 18);
  setFont(doc, fonts, 'regular', 10, COLORS.ink);
  doc.text(analysis.summary || call.analysis_summary || 'Summary not available.', 58, y + 18, {
    width: doc.page.width - 116
  });
  doc.y = y + 96;
}

function drawAnalysisMetrics(doc, fonts, analysis, watermarkText) {
  drawSectionTitle(doc, fonts, 'Call Metrics', 'Duration, sentiment, and quality indicators', watermarkText);
  ensureSpace(doc, fonts, watermarkText, 126);
  const metrics = analysis.metrics || {};
  const cards = [
    ['Sentiment', `${analysis.sentiment || 'neutral'} (${Math.round(Number(analysis.sentiment_score || 0) * 100)}%)`],
    ['Duration', formatDuration(metrics.total_duration)],
    ['AI Talk Time', formatDuration(metrics.ai_talk_time)],
    ['Patient Talk Time', formatDuration(metrics.patient_talk_time)],
    ['Questions Asked', String(metrics.questions_asked || 0)],
    ['Questions Answered', String(metrics.questions_answered || 0)]
  ];
  const y = doc.y;
  const cardWidth = (doc.page.width - 104) / 3;
  cards.forEach((card, index) => {
    const x = 40 + (index % 3) * (cardWidth + 12);
    const rowY = y + Math.floor(index / 3) * 58;
    drawPanel(doc, x, rowY, cardWidth, 46, COLORS.panel, COLORS.line, 12);
    setFont(doc, fonts, 'regular', 8, COLORS.muted);
    doc.text(card[0], x + 12, rowY + 10, { width: cardWidth - 24 });
    setFont(doc, fonts, 'heading', 10, COLORS.ink);
    doc.text(card[1], x + 12, rowY + 25, { width: cardWidth - 24 });
  });
  doc.y = y + 128;
}

function drawAnalysisOutcomes(doc, fonts, analysis, watermarkText) {
  drawSectionTitle(doc, fonts, 'Key Outcomes', 'Structured information extracted from the call', watermarkText);
  const rows = Array.isArray(analysis.outcome_cards) ? analysis.outcome_cards : [];
  if (!rows.length) {
    drawBulletList(doc, fonts, [], watermarkText, 'No key outcomes were extracted.');
    return;
  }
  rows.forEach((row) => {
    ensureSpace(doc, fonts, watermarkText, 42);
    const y = doc.y;
    drawPanel(doc, 40, y, doc.page.width - 80, 34, COLORS.panel, COLORS.line, 10);
    setFont(doc, fonts, 'regular', 9, COLORS.muted);
    doc.text(row.label, 56, y + 11, { width: 190 });
    setFont(doc, fonts, 'heading', 10, COLORS.ink);
    doc.text(String(row.value || ''), 250, y + 11, { width: doc.page.width - 306 });
    doc.y = y + 42;
  });
}

function drawAnalysisTranscript(doc, fonts, turns, watermarkText) {
  drawSectionTitle(doc, fonts, 'Transcript', 'Speaker-separated conversation', watermarkText);
  const safeTurns = Array.isArray(turns) ? turns : [];
  if (!safeTurns.length) {
    drawBulletList(doc, fonts, [], watermarkText, 'Transcript not available.');
    return;
  }
  safeTurns.slice(0, 40).forEach((turn) => {
    const role = turn.role === 'AI' ? 'AI' : turn.role === 'PATIENT' ? 'Patient' : turn.role || 'Note';
    const text = String(turn.text || '');
    const height = Math.max(44, doc.heightOfString(text, { width: doc.page.width - 150 }) + 26);
    ensureSpace(doc, fonts, watermarkText, height + 8);
    const y = doc.y;
    drawPanel(doc, 40, y, doc.page.width - 80, height, role === 'AI' ? COLORS.blueSoft : COLORS.panel, COLORS.line, 12);
    setFont(doc, fonts, 'heading', 9, role === 'AI' ? COLORS.blue : COLORS.green);
    doc.text(role, 56, y + 12, { width: 80 });
    setFont(doc, fonts, 'regular', 9, COLORS.ink);
    doc.text(text, 130, y + 12, { width: doc.page.width - 190 });
    doc.y = y + height + 8;
  });
}

function generateCallAnalysisPDF({ call, analysis }) {
  return new Promise((resolve, reject) => {
    try {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const reportPath = `/tmp/call_analysis_${call.id || timestamp}_${timestamp}.pdf`;
      const doc = new PDFDocument({ margin: 40, size: 'A4', autoFirstPage: true });
      const stream = fs.createWriteStream(reportPath);
      const fonts = registerFonts(doc);
      const watermarkText = process.env.CLIENT_NAME || 'Call Analysis';

      doc.pipe(stream);
      decoratePage(doc, fonts, watermarkText);
      drawCallAnalysisHeader(doc, fonts, call, analysis, watermarkText);
      drawAnalysisSummary(doc, fonts, call, analysis, watermarkText);
      drawAnalysisMetrics(doc, fonts, analysis, watermarkText);
      drawAnalysisOutcomes(doc, fonts, analysis, watermarkText);
      drawAnalysisTranscript(doc, fonts, analysis.transcript_turns || [], watermarkText);
      doc.end();

      stream.on('finish', () => resolve(reportPath));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = {
  generateReportPDF,
  generateCallAnalysisPDF
};
