const mongoose = require('mongoose');

const customerSchema = new mongoose.Schema({
  tenantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Tenant',
    required: true
  },
  name: { type: String, required: true },
  phone: { type: String, required: true },
  preferred_slot: { type: String, default: '10:00' },
  status: { type: String, default: 'pending' },
  archived_at: { type: Date, default: null },
  archived_by: { type: String, default: null },
  archive_reason: { type: String, default: null },
  pre_archive_status: { type: String, default: null },
  customer_value: { type: String, default: 'standard' },
  urgency_level: { type: String, default: 'normal' },
  priority_score: { type: Number, default: 50 },
  ai_score: { type: Number, default: 50 },
  preferred_language: { type: String, default: 'hi' },
  preferred_dialect: { type: String },
  do_not_call: { type: Number, default: 0 },
  consent_status: { type: String, default: 'unknown' },
  last_contact_outcome: { type: String },
  scheduled_datetime: { type: Date },
  next_retry_at: { type: Date },
  retry_count: { type: Number, default: 0 },
  wrong_number_flag: { type: Number, default: 0 },
  admin_review_required: { type: Number, default: 0 },
  callback_requested_at: { type: Date },
  last_called_at: { type: Date },
  best_call_slot: { type: String },
  last_pickup_slot: { type: String },
  pickup_rate_score: { type: Number, default: 0 },
  outstanding_issues: { type: String },
  pending_follow_ups: { type: String },
  last_sentiment_score: { type: Number },
  last_sentiment_label: { type: String },
  revenue_stage: { type: String, default: 'unassigned' },
  revenue_estimate: { type: Number, default: 0 },
  campaign_name: { type: String },
  service_interest: { type: String },
  call_type: { type: String, default: 'REVIEW_CALL' },
  last_competitor_mention: { type: String },
  data_retention_until: { type: Date },
  dnd_checked_at: { type: Date },
  default_agent_id: { type: mongoose.Schema.Types.ObjectId, ref: 'Agent' },
  video_sent: { type: Number, default: 0 },
  attempt_count: { type: Number, default: 0 },
  last_attempt_at: { type: Date },
  next_attempt_at: { type: Date },
  failed_reason: { type: String },
  scheduled_at: { type: Date },
  phone_number: { type: String },
  normalized_phone: { type: String },
  auto_retry_enabled: { type: Number, default: 0 },
  locked_at: { type: Date },
  provider_request_id: { type: String },
  is_manual: { type: Number, default: 0 },
  last_visit_date: { type: Date }
}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

module.exports = mongoose.model('Customer', customerSchema);
