begin;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'ai_call_agent_runtime') then
    create role ai_call_agent_runtime
      nologin
      nosuperuser
      nocreatedb
      nocreaterole
      noreplication
      nobypassrls;
  end if;
end
$$;

create table public.clients (
  id bigint generated by default as identity primary key,
  slug text not null,
  name text not null,
  status text not null default 'active' check (status in ('active', 'inactive')),
  timezone text not null default 'UTC',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clients_slug_unique unique (slug)
);

create table public.app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  username_normalized text not null,
  email text not null,
  email_normalized text not null,
  active boolean not null default true,
  auth_version integer not null default 1 check (auth_version >= 1),
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_users_username_normalized_unique unique (username_normalized),
  constraint app_users_email_normalized_unique unique (email_normalized)
);

create table public.app_user_roles (
  user_id uuid not null references public.app_users(id) on delete cascade,
  role text not null check (role in ('webmaster')),
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table public.customers (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name varchar(100) not null,
  phone varchar(32) not null,
  preferred_slot varchar(10) not null default '10:00',
  status varchar(40) not null default 'pending',
  customer_value varchar(20) not null default 'standard',
  urgency_level varchar(20) not null default 'normal',
  priority_score integer not null default 50,
  ai_score integer not null default 50,
  preferred_language varchar(20) not null default 'hi',
  preferred_dialect varchar(40),
  do_not_call boolean not null default false,
  consent_status varchar(20) not null default 'unknown',
  last_contact_outcome varchar(40),
  next_retry_at timestamptz,
  retry_count integer not null default 0 check (retry_count >= 0),
  wrong_number_flag boolean not null default false,
  admin_review_required boolean not null default false,
  callback_requested_at timestamptz,
  last_called_at timestamptz,
  best_call_slot varchar(10),
  last_pickup_slot varchar(10),
  pickup_rate_score integer not null default 0,
  outstanding_issues text,
  pending_follow_ups text,
  last_sentiment_score double precision,
  last_sentiment_label varchar(20),
  revenue_stage varchar(30) not null default 'unassigned',
  revenue_estimate numeric(14,2) not null default 0,
  last_competitor_mention text,
  data_retention_until timestamptz,
  dnd_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customers_client_phone_unique unique (client_id, phone),
  constraint customers_client_id_id_unique unique (client_id, id)
);

create table public.calls (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  customer_id bigint not null,
  called_at timestamptz,
  outcome varchar(40),
  outcome_detail varchar(40),
  twilio_sid varchar(100),
  whatsapp_sent boolean not null default false,
  transcript_text text,
  consent_detected boolean not null default false,
  language varchar(20),
  extracted_rating integer check (extracted_rating between 1 and 5),
  extracted_review_text text,
  feedback_saved_at timestamptz,
  recording_sid varchar(100),
  recording_url text,
  recording_status varchar(30),
  transcript_status varchar(30) not null default 'pending',
  transcript_source varchar(20),
  analysis_status varchar(30) not null default 'pending',
  analysis_summary text,
  analysis jsonb,
  key_points jsonb,
  report_excerpt text,
  analysis_completed_at timestamptz,
  fallback_triggered boolean not null default false,
  sentiment_label varchar(20),
  sentiment_score double precision,
  hot_lead_score integer not null default 0,
  next_action_at timestamptz,
  follow_up_task text,
  recording_download_status varchar(30) not null default 'pending',
  crm_sync_status varchar(30) not null default 'pending',
  whatsapp_summary_sent boolean not null default false,
  revenue_attribution_status varchar(30) not null default 'pending',
  call_script_version varchar(40) not null default 'hindi-feedback-v1',
  competitor_mentions jsonb,
  objections jsonb,
  interest_detected boolean not null default false,
  callback_requested boolean not null default false,
  human_escalation_requested boolean not null default false,
  supervisor_alert_level varchar(20) not null default 'normal',
  supervisor_notes text,
  consent_message_played boolean not null default false,
  recording_consent_captured boolean not null default false,
  invoice_triggered boolean not null default false,
  proposal_triggered boolean not null default false,
  live_sentiment_score double precision,
  live_sentiment_label varchar(20),
  live_red_flag boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint calls_client_customer_fk
    foreign key (client_id, customer_id)
    references public.customers (client_id, id)
    on delete cascade,
  constraint calls_client_id_id_unique unique (client_id, id),
  constraint calls_payload_size_check check (
    octet_length(
      coalesce(transcript_text, '') ||
      coalesce(analysis::text, '') ||
      coalesce(key_points::text, '') ||
      coalesce(competitor_mentions::text, '') ||
      coalesce(objections::text, '')
    ) <= 2097152
  )
);

create unique index calls_twilio_sid_unique
  on public.calls (twilio_sid)
  where twilio_sid is not null;

create table public.feedback (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  customer_id bigint not null,
  call_id bigint,
  review_text text,
  category varchar(20),
  stars integer check (stars between 1 and 5),
  source varchar(20) not null default 'manual',
  submitted_at timestamptz not null default now(),
  constraint feedback_client_customer_fk
    foreign key (client_id, customer_id)
    references public.customers (client_id, id)
    on delete cascade,
  constraint feedback_client_call_fk
    foreign key (client_id, call_id)
    references public.calls (client_id, id)
    on delete cascade
);

create unique index feedback_call_id_unique
  on public.feedback (call_id)
  where call_id is not null;

create table public.call_supervisor_events (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  call_id bigint not null,
  event_type varchar(40) not null,
  severity varchar(20) not null default 'info',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint call_supervisor_events_client_call_fk
    foreign key (client_id, call_id)
    references public.calls (client_id, id)
    on delete cascade
);

create table public.application_state (
  client_id bigint references public.clients(id) on delete cascade,
  key text not null,
  value jsonb,
  version integer not null default 1 check (version >= 1),
  updated_at timestamptz not null default now(),
  constraint application_state_scope_key_unique unique nulls not distinct (client_id, key)
);

create table public.agents (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  provider text,
  model text,
  voice text,
  language varchar(20),
  prompt_version text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agents_client_id_id_unique unique (client_id, id)
);

create table public.campaign_configurations (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  agent_id bigint,
  name text not null,
  status text not null default 'draft' check (status in ('draft', 'active', 'paused', 'archived')),
  schedule_policy jsonb not null default '{}'::jsonb,
  retry_policy jsonb not null default '{}'::jsonb,
  script_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaign_configurations_client_agent_fk
    foreign key (client_id, agent_id)
    references public.agents (client_id, id)
    on delete set null
);

create table public.support_tickets (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  customer_id bigint,
  call_id bigint,
  title text not null,
  description text,
  status text not null default 'open' check (status in ('open', 'in_progress', 'resolved', 'closed')),
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  assignee_user_id uuid references public.app_users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint support_tickets_client_customer_fk
    foreign key (client_id, customer_id)
    references public.customers (client_id, id)
    on delete set null,
  constraint support_tickets_client_call_fk
    foreign key (client_id, call_id)
    references public.calls (client_id, id)
    on delete set null
);

create index clients_status_name_idx on public.clients (status, name);
create index customers_priority_idx on public.customers (client_id, priority_score desc, created_at desc);
create index customers_retry_idx on public.customers (client_id, next_retry_at) where next_retry_at is not null;
create index customers_schedule_idx on public.customers (client_id, preferred_slot, status);
create index customers_workflow_idx on public.customers (client_id, status, do_not_call, admin_review_required);
create index calls_customer_history_idx on public.calls (client_id, customer_id, called_at desc);
create index calls_recent_idx on public.calls (client_id, called_at desc);
create index calls_outcome_idx on public.calls (client_id, outcome, called_at desc);
create index calls_pipeline_recovery_idx on public.calls (client_id, transcript_status, analysis_status, created_at);
create index feedback_customer_idx on public.feedback (client_id, customer_id, submitted_at desc);
create index feedback_recent_idx on public.feedback (client_id, submitted_at desc);
create index supervisor_events_call_idx on public.call_supervisor_events (client_id, call_id, created_at desc);
create index supervisor_events_severity_idx on public.call_supervisor_events (client_id, severity, created_at desc);
create index agents_status_idx on public.agents (client_id, status, name);
create index campaign_configurations_status_idx on public.campaign_configurations (client_id, status, name);
create index support_tickets_status_idx on public.support_tickets (client_id, status, priority, created_at desc);

grant usage on schema public to ai_call_agent_runtime;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'clients',
    'app_users',
    'app_user_roles',
    'customers',
    'calls',
    'feedback',
    'call_supervisor_events',
    'application_state',
    'agents',
    'campaign_configurations',
    'support_tickets'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all privileges on table public.%I from public, anon, authenticated, service_role', table_name);
    execute format('grant select, insert, update, delete on table public.%I to ai_call_agent_runtime', table_name);
    execute format(
      'create policy %I on public.%I for all to ai_call_agent_runtime using (true) with check (true)',
      table_name || '_runtime_all',
      table_name
    );
  end loop;
end
$$;

revoke all privileges on all sequences in schema public from public, anon, authenticated, service_role;
grant usage, select on all sequences in schema public to ai_call_agent_runtime;

alter default privileges in schema public revoke all on tables from anon, authenticated, service_role;
alter default privileges in schema public revoke all on sequences from anon, authenticated, service_role;

commit;
